import { type Node, type Edge, MarkerType } from "@xyflow/svelte";

export const initialNodes: Node[] = [
  {
    id: "start",
    position: { x: -82, y: 23 },
    data: { label: "Start" },
    type: "start",
  },
  {
    id: "discovery",
    position: { x: 24, y: -6 },
    data: { label: "Discovery" },
    type: "custom",
  },
  {
    id: "proposal",
    position: { x: 200, y: -15 },
    data: { label: "Proposal" },
    type: "custom",
  },
  {
    id: "research",
    position: { x: 337, y: 55 },
    data: { label: "Research" },
    type: "custom",
  },
  {
    id: "design",
    position: { x: 118, y: 88 },
    data: { label: "Design" },
    type: "custom",
  },
  {
    id: "good",
    position: { x: 5, y: 133 },
    data: { label: "Good?" },
    type: "decision",
  },
  {
    id: "develop",
    position: { x: 299, y: 167 },
    data: { label: "Develop" },
    type: "custom",
  },
  {
    id: "works",
    position: { x: 251, y: 256 },
    data: { label: "Works?" },
    type: "decision",
  },
  {
    id: "launch",
    position: { x: 71, y: 264 },
    data: { label: "Launch" },
    type: "custom",
  },
  {
    id: "perfect",
    position: { x: -135, y: 190 },
    data: { label: "Perfect?" },
    type: "decision",
  },
];

export const initialEdges: Edge[] = [
  // start → discovery
  {
    id: "estart-discovery",
    source: "start",
    target: "discovery",
    animated: false,
    type: "standard",
    sourceHandle: "b",
    targetHandle: "d",
    markerEnd: "sketchedArrow",
  },
  // flow steps
  {
    id: "ediscovery-proposal",
    source: "discovery",
    target: "proposal",
    animated: false,
    type: "standard",
    sourceHandle: "b",
    targetHandle: "d",
    markerEnd: "sketchedArrow",
  },
  {
    id: "eproposal-research",
    source: "proposal",
    target: "research",
    animated: false,
    type: "standard",
    sourceHandle: "b",
    targetHandle: "d",
    markerEnd: "sketchedArrow",
  },
  {
    id: "eresearch-design",
    source: "research",
    target: "design",
    animated: false,
    type: "standard",
    sourceHandle: "c",
    targetHandle: "a",
    markerEnd: "sketchedArrow",
  },
  {
    id: "edesign-good",
    source: "design",
    target: "good",
    animated: false,
    type: "standard",
    sourceHandle: "d",
    targetHandle: "a",
    markerEnd: "sketchedArrow",
  },
  {
    id: "egood-develop",
    source: "good",
    target: "develop",
    animated: false,
    type: "standard",
    sourceHandle: "c",
    targetHandle: "d",
    label: "Yes",
    markerEnd: "sketchedArrow",
  },
  {
    id: "edevelop-works",
    source: "develop",
    target: "works",
    animated: false,
    type: "standard",
    sourceHandle: "b",
    targetHandle: "b",
    markerEnd: "sketchedArrow",
  },
  {
    id: "eworks-launch",
    source: "works",
    target: "launch",
    animated: false,
    type: "standard",
    sourceHandle: "d",
    targetHandle: "b",
    label: "Yes",
    markerEnd: "sketchedArrow",
  },
  {
    id: "elaunch-perfect",
    source: "launch",
    target: "perfect",
    animated: false,
    type: "standard",
    sourceHandle: "d",
    targetHandle: "b",
    markerEnd: "sketchedArrow",
  },
  // decision loops (“No”)
  {
    id: "egood-design",
    source: "good",
    target: "design",
    label: "No",
    animated: false,
    type: "standard",
    sourceHandle: "b",
    targetHandle: "c",
    markerEnd: "sketchedArrow",
  },
  {
    id: "eworks-develop",
    source: "works",
    target: "develop",
    label: "No",
    animated: false,
    type: "standard",
    sourceHandle: "a",
    targetHandle: "c",
    markerEnd: "sketchedArrow",
  },
  {
    id: "eperfect-start",
    source: "perfect",
    target: "start",
    animated: false,
    type: "standard",
    sourceHandle: "a",
    targetHandle: "c",
    markerEnd: "sketchedArrow",
  },
];
